let name = prompt("이름을 입력하세요")
let drink = prompt("메뉴를 입력하세요")
let amount = prompt("수량을 입력하세요")

console.log("[주문 접수]")
console.log("이름 ")
console.log(name)
console.log("메뉴")
console.log(drink)
console.log("수량 ")
console.log(amount)